@startuml config-general
skinparam BackgroundColor FFFFFE

' default arrow style
skinparam arrow {
  Color Black
  FontColor Black
}

' default note style
skinparam note {
    BackgroundColor Khaki
    BorderColor Khaki
    FontColor Black
}

' presets for packages
skinparam package {
  BackgroundColor #E0E0E0
  BorderColor #E0E0E0
  FontStyle italic bold
  Shadowing false

  BackgroundColor<<Green>> MediumSeaGreen
  BorderColor<<Green>> MediumSeaGreen

  BackgroundColor<<DarkSalmon>> DarkSalmon
  BorderColor<<DarkSalmon>> DarkSalmon

  BackgroundColor<<CadetBlue>> CadetBlue
  BorderColor<<CadetBlue>> CadetBlue

  BackgroundColor<<Gold>> Gold
  BorderColor<<Gold>> Gold

  BackgroundColor<<LimeGreen>> LimeGreen
  BorderColor<<LimeGreen>> LimeGreen
}

' presets for components
skinparam component {
  ' function specific styling
  BackgroundColor<<Exchange>> DeepSkyBlue
  BorderColor<<Exchange>> DeepSkyBlue
  BackgroundColor<<Service>> TECHNOLOGY
  BorderColor<<Service>> TECHNOLOGY
  BackgroundColor<<Queue>> Gold
  BorderColor<<Queue>> Gold

  ' DeepSkyBlue
  BackgroundColor<<DeepSkyBlue>> DeepSkyBlue
  BorderColor<<DeepSkyBlue>> DeepSkyBlue
  FontColor<<Green>> Black

  ' Green
  BackgroundColor<<Green>> Green
  BorderColor<<Green>> Green
  FontColor<<Green>> Black

  ' Gold
  BackgroundColor<<Gold>> Gold
  BorderColor<<Gold>> Gold
  FontColor<<Gold>> Black

  ' DimGrey
  BackgroundColor<<DimGrey>> DimGrey
  BorderColor<<DimGrey>> DimGrey
  FontColor<<DimGrey>> GhostWhite

  ' PaleVioletRed
  BackgroundColor<<PaleVioletRed>> PaleVioletRed
  BorderColor<<PaleVioletRed>> PaleVioletRed
  FontColor<<PaleVioletRed>> Black

  ' DarkRed
  BackgroundColor<<DarkRed>> DarkRed
  BorderColor<<DarkRed>> DarkRed
  FontColor<<DarkRed>> FloralWhite

  ' SlateBlue
  BackgroundColor<<SlateBlue>> SlateBlue
  BorderColor<<SlateBlue>> SlateBlue
  FontColor<<SlateBlue>> FloralWhite
}
@enduml
